version: '3' 

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db:/var/lib/sqlite3
      
  web:
    build: 
      context: .
      dockerfile: "Dev.Dockerfile"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/my_app
    ports:
      - 8080:8080
    depends_on:
      - db
    tty: true
    stdin_open: true