default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test
  
production:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DB_DATABASENAME") { 'my_app' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  timeout: 5000
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>
